### ISSUE TITLE
Missing keys nova 2.5

### ISSUE THREAD

**Issue by m-lotze** [franzdumfart/laravel-nova-localizations#110]
Hi there,

nova 2.5 added some keys in the json files:

```
"All resources loaded.": "All resources loaded.",
"Load :perPage More": "Load :perPage More",
":amount Total": ":amount Total",
"Show All Fields": "Show All Fields",
"There was a problem submitting the form.": "There was a problem submitting the form.",
"There was a problem executing the action.": "There was a problem executing the action.",
"*": "*"
```

it would be nice if these are added to translations as well.

**Comment by franzdumfart** [comment]
I've added these new fields for the german and english language files. You can ping previous contributors on this repo (check on the readme file) to get support for specific languages.

Closes with https://github.com/franzdumfart/laravel-nova-localizations/commit/ffc4b1527082af21272e7d0c921669b69080f782.
