### ISSUE TITLE
Create Title not translated

### ISSUE THREAD

**Issue by NormanHuth** [franzdumfart/laravel-nova-localizations#113]
When creating the title is not translated.

![Unbenannt](https://user-images.githubusercontent.com/26193232/78223260-dee33400-74c6-11ea-9b1e-a4b1dc6bf107.png)

**Comment by franzdumfart** [comment]
Hello Norman, I have to admin that I currently have no Nova installation running on my projects. Maybe some previous supporter can help. Maybe @mrmonat, @pajoda, @dastiii, @hofmannsven or @renky?

Thanks in advance!

**Comment by dastiii** [comment]
I can't reproduce the problem using Nova 3.3.0 and the latest de.json.

**Comment by hofmannsven** [comment]
@dastiii Same for me. Seems to work just fine.
@NormanHuth How did you register the label?

**Comment by NormanHuth** [comment]
I just put on a test app and there it works. So it can be closed, because the bug is definitely not in the package.
