### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by fede91it** [franzdumfart/laravel-nova-localizations#69]
Although in resources/lang/vendor/nova there are the files for the Italian language (folder and json), Nova keeps showing me the strings in English.

The Laravel app language is set to 'it' and the fallback language to 'en'.

What's wrong?

**Comment by franzdumfart** [comment]
Very strange. Can you try to set another language (including their files) and see if it works with them? Can you also verify that you completed all steps documented here? https://nova.laravel.com/docs/1.0/customization/localization.html

**Comment by s3b4stian** [comment]
Hi, I will check the translation file for errors!

**Comment by s3b4stian** [comment]
I checked `/lang/it.json` and `/lang/it/validation.php` and seem there isn't errors

**Comment by fede91it** [comment]
For you what could be the cause?

**Comment by s3b4stian** [comment]
Unfortunately, I don't have a Nova license and I cannot check if language works.

If the package is correctely installed and If you have the possibility, try to debug code for understand because the language returns to fallback.

Finally, language file is for version 1.1.4, check your.

**Comment by s3b4stian** [comment]
Language file updated to 1.2.0, could you try if it works?

**Comment by blyleven** [comment]
I'm having the same issue when using several locales. The sidebar is updating just fine, but all texts in the right side of the screen, like searchbar, pagination and buttons are not translated. Using the latest version of Nova.

**Comment by fede91it** [comment]
This is weird... maybe it's a Nova issue?

**Comment by blyleven** [comment]
I managed to solve the issue on my end. I used a middleware which would update the app locale. I don't know why, but that clearly did not translate all texts. After placing this piece of code in the boot function of the NovaServiceProvider it worked.

Nova::serving(function (ServingNova $event) {
    app()->setLocale('nl');
});

**Comment by fede91it** [comment]
For me it doesn't work also with that snippet in the nova provider

What the hell?

**Comment by cchsu23** [comment]
I have the same problem,too.

**Comment by fede91it** [comment]
For me the issue was caused by the /nova entry point, that in my case was /cp and this created a conflict with mcamara/laravel-localization because it intended /cp as the language segment in the url
