### ISSUE TITLE
please add Azerbaijan language

### ISSUE THREAD

**Issue by Energon7** [franzdumfart/laravel-nova-localizations#71]

**Comment by franzdumfart** [comment]
Hi @Energon7! You are very welcome to open a PR with this language. It's very hard to create a localization for a foreign language. The only way for me is to use Google translate, which is not perfect at all. If you have any questions with creating a new language file, submitting a PR or stuff like this, I would love to help!

**Comment by Energon7** [comment]
[az.zip](https://github.com/franzdumfart/laravel-nova-localizations/files/2574989/az.zip)

**Comment by franzdumfart** [comment]
Thanks a lot! Added with https://github.com/franzdumfart/laravel-nova-localizations/commit/e9a0ffc873309e6b1dbb4936c2ee894f5346752a.
