### ISSUE TITLE
Flipping the Nova direction to RTL

### ISSUE THREAD

**Issue by AlShahawi** [franzdumfart/laravel-nova-localizations#82]
Some language directions such as Arabic is RTL. Any ideas for how to flip the CSS stylesheets to be in the RTL direction using a tool like [https://rtlcss.com](RTLCSS) ?

**Comment by hofmannsven** [comment]
@AlShahawi I think you're better off asking this question in the [Nova Issue Tracker](https://github.com/laravel/nova-issues) on GitHub. 

This issue seems related: laravel/nova-issues#1039
